# Generated by Django 6.0.2 on 2026-03-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_earnings_user_pending_withdraw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
