# Generated by Django 6.0.2 on 2026-04-06 17:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_earnings',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='earnings',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='pending_withdraw',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_withdrawn',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=10),
        ),
    ]
