# Generated by Django 6.0.2 on 2026-04-06 17:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicks', '0001_initial'),
        ('links', '0003_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickevent',
            name='cpm_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='earned_amount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['short_link', 'created_at'], name='clicks_clic_short_l_736253_idx'),
        ),
    ]
