# Generated by Django 6.0.2 on 2026-04-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monetizationrule',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
