# Generated by Django 6.0.2 on 2026-04-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_alter_monetizationrule_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='monetizationrule',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monetizationrule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
